### ISSUE TITLE
Issue while installing fabtools3 inside a container.

### ISSUE THREAD

**Issue by tabka** [fabtools/fabtools#351]
Hello,
I have a problem while running "pip3 install fabtools3" I have the following error and I don't know if it's a bug related to fabtools3 or I have a missing package , and I couldn't find a solution to make it work and my app depends on it:

`Removing intermediate container 0df323c3f499
Step 3/6 : RUN pip install --upgrade pip
 ---> Running in d7040d887caa
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-9.0.1
 ---> e9f733ecb5fe
Removing intermediate container d7040d887caa
Step 4/6 : RUN pip3 install --upgrade pip
 ---> Running in 110b486c4093
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-9.0.1
 ---> 91d2aa846c6d
Removing intermediate container 110b486c4093
Step 5/6 : RUN pip3 -V
 ---> Running in 5b057f4f3d14
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
 ---> e57875700319
Removing intermediate container 5b057f4f3d14
Step 6/6 : RUN pip3 install fabtools3
 ---> Running in 84991a3a60f4
Collecting fabtools3
  Downloading fabtools3-0.19.0.tar.gz (96kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-94zykfa6/fabtools3/setup.py", line 36, in <module>
        long_description=read('README.rst') + '\n' + read('docs/CHANGELOG.rst'),
      File "/tmp/pip-build-94zykfa6/fabtools3/setup.py", line 16, in read
        return open(path).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 681: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-94zykfa6/fabtools3/
The command '/bin/sh -c pip3 install fabtools3' returned a non-zero code: 1
`

Here's an example of the Dockerfile to reproduce the issue :
`FROM ubuntu:16.04
RUN apt-get update && apt-get install -y python-pip \
    python3-pip \
    python-dev \
    python3-dev \
    python-setuptools
RUN pip install --upgrade pip
RUN pip3 install --upgrade pip
RUN pip3 -V
RUN pip3 install fabtools3
`

docker version:
`root@deployer:~# docker -v
Docker version 17.03.1-ce, build c6d412e
`
I have the same issue even if I install the package inside a virtualenv.

Thank you for your help.

**Comment by tabka** [comment]
I made a test when I clone the fabtools3 project inside the container and try to open the CHANGELOG.rst file I get the same issue from the python interpreter ,So maybe there's something that need to be changed in the file.

From the container:
`
>>> with open("/tmp/fabtools/docs/CHANGELOG.rst", 'r') as f:                                                                                                                                                                                  
...     txt = f.read()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1216: ordinal not in range(128)
`
