### ISSUE TITLE
error on  add_ssh_public_key

### ISSUE THREAD

**Issue by zodman** [fabtools/fabtools#366]
i had:

`fabtools.user.add_ssh_public_key("web", "id_rsa_deploy.pub")`

traceback:

```
sudo: touch "/export/web/.ssh/authorized_keys"
Traceback (most recent call last):
  File "/home/zodman/.virtualenvs/provision/local/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/home/zodman/.virtualenvs/provision/local/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/home/zodman/.virtualenvs/provision/local/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/home/zodman/.virtualenvs/provision/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/zodman/work/sysadmin_interalia/provision/fabfile.py", line 47, in install
    fabtools.user.add_ssh_public_key("web", [ "id_rsa_deploy.pub",])
  File "/home/zodman/.virtualenvs/provision/src/fabtools/fabtools/user.py", line 236, in add_ssh_public_key
    add_ssh_public_keys(name, [filename])
  File "/home/zodman/.virtualenvs/provision/src/fabtools/fabtools/user.py", line 267, in add_ssh_public_keys
    use_sudo=True)
  File "/home/zodman/.virtualenvs/provision/src/fabtools/fabtools/require/files.py", line 201, in file
    func('chmod %(mode)o "%(path)s"' % locals())
TypeError: %o format: a number is required, not str
```
posible fix:

```
    if mode and _mode(path, use_sudo) != mode:
        if isinstance(mode, str):
            mode = int(mode)
        func('chmod %(mode)o "%(path)s"' % locals())
```

**Comment by zodman** [comment]
PR #368

**Comment by qqalexqq** [comment]
+1 for merge
